server:
  port: 8081

curator:
  retryCount: 5                   #重试次数
  elapsedTimeMs: 5000             #重试间隔时间
  connectString: 129.211.26.83:2181   # zookeeper 地址
  sessionTimeoutMs: 60000         # session超时时间
  connectionTimeoutMs: 5000       # 连接超时时间